name: NASA project CI
on:
  push:
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true # will disable watch mode from the react tests for example
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        mongodb-version: ["4.4"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run setup
      - run: npm run build --prefix client
      - run: npm test
